services:
  app:
    build: .
    container_name: minha_api
    restart: always
    ports:
      - 3080:3080
    env_file:
    - .env
    depends_on:
    - mongo
  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: